//AssetsManagement

//Get Assets
export const GET_ASSETS = "GET_ASSETS";
export const GET_ASSETS_SUCCESS = "GET_ASSETS_SUCCESS";
export const GET_ASSETS_FAIL = "GET_ASSETS_FAIL";

//Get Asset
export const GET_ASSET_OVERVIEW = "GET_ASSET_OVERVIEW";
export const GET_ASSET_OVERVIEW_SUCCESS = "GET_ASSET_OVERVIEW_SUCCESS";
export const GET_ASSET_OVERVIEW_FAIL = "GET_ASSET_OVERVIEW_FAIL";

//Add Assets

export const ADD_NEW_ASSET = "ADD_NEW_ASSET";
export const ADD_ASSET_SUCCESS = "ADD_ASSET_SUCCESS";
export const ADD_ASSET_FAIL = "ADD_ASSET_FAIL";

//Edit or Update Assets

export const UPDATE_ASSET = "UPDATE_ASSET";
export const UPDATE_ASSET_SUCCESS = "UPDATE_ASSET_SUCCESS";
export const UPDATE_ASSET_FAIL = "UPDATE_ASSET_FAIL";

// Delete Assets

export const DELETE_ASSET = "DELETE_ASSET";
export const DELETE_ASSET_SUCCESS = "DELETE_ASSET_SUCCESS";
export const DELETE_ASSET_FAIL = "DELETE_ASSET_FAIL";
