/* EMPLOYEE PROFILE */
export const GET_EMPLOYEE_PROFILE = "GET_EMPLOYEE_PROFILE";
export const GET_EMPLOYEE_PROFILE_SUCCESS = "GET_EMPLOYEE_PROFILE_SUCCESS";
export const GET_EMPLOYEE_PROFILE_FAIL = "GET_EMPLOYEE_PROFILE_FAIL";
