//CompanySettingsManagement

//Get CompanySettings
export const GET_COMPANY_SETTINGS = "GET_COMPANY_SETTINGS";
export const GET_COMPANY_SETTINGS_SUCCESS = "GET_COMPANY_SETTINGS_SUCCESS";
export const GET_COMPANY_SETTINGS_FAIL = "GET_COMPANY_SETTINGS_FAIL";

//Add CompanySettings

export const ADD_NEW_COMPANY_SETTING = "ADD_NEW_COMPANY_SETTING";
export const ADD_COMPANY_SETTING_SUCCESS = "ADD_COMPANY_SETTING_SUCCESS";
export const ADD_COMPANY_SETTING_FAIL = "ADD_COMPANY_SETTING_FAIL";

//Edit or Update CompanySettings

export const UPDATE_COMPANY_SETTING = "UPDATE_COMPANY_SETTING";
export const UPDATE_COMPANY_SETTING_SUCCESS = "UPDATE_COMPANY_SETTING_SUCCESS";
export const UPDATE_COMPANY_SETTING_FAIL = "UPDATE_COMPANY_SETTING_FAIL";

// Delete CompanySettings

export const DELETE_COMPANY_SETTING = "DELETE_COMPANY_SETTING";
export const DELETE_COMPANY_SETTING_SUCCESS = "DELETE_COMPANY_SETTING_SUCCESS";
export const DELETE_COMPANY_SETTING_FAIL = "DELETE_COMPANY_SETTING_FAIL";
