/* USERS */
export const GET_USERS = "GET_USERS";
export const GET_APPROVERS = "GET_APPROVERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";
export const GET_APPROVERS_SUCCESS = "GET_APPROVERS_SUCCESS";
export const GET_APPROVERS_FAIL = "GET_APPROVERS_FAIL";

/* USERS PROFILE */
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_APPROVER_PROFILE = "GET_APPROVER_PROFILE";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_APPROVER_PROFILE_SUCCESS = "GET_APPROVER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAIL = "GET_USER_PROFILE_FAIL";
export const GET_APPROVER_PROFILE_FAIL = "GET_APPROVER_PROFILE_FAIL";

/**
 * add user
 */
export const ADD_NEW_USER = "ADD_NEW_USER";
export const ADD_NEW_APPROVER = "ADD_NEW_APPROVER";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_APPROVER_SUCCESS = "ADD_APPROVER_SUCCESS";
export const ADD_USER_FAIL = "ADD_USER_FAIL";
export const ADD_APPROVER_FAIL = "ADD_APPROVER_FAIL";

/**
 * Edit user
 */
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_APPROVER = "UPDATE_APPROVER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_APPROVER_SUCCESS = "UPDATE_APPROVER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
export const UPDATE_APPROVER_FAIL = "UPDATE_APPROVER_FAIL";

/**
 * Delete user
 */
export const DELETE_USER = "DELETE_USER";
export const DELETE_APPROVER = "DELETE_APPROVER";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_APPROVER_SUCCESS = "DELETE_APPROVER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_APPROVER_FAIL = "DELETE_APPROVER_FAIL";

//RolesManagement

//Get Roles
export const GET_ROLES = "GET_ROLES";
export const GET_ROLES_SUCCESS = "GET_ROLES_SUCCESS";
export const GET_ROLES_FAIL = "GET_ROLES_FAIL";

//Add Roles

export const ADD_NEW_ROLE = "ADD_NEW_ROLE";
export const ADD_ROLE_SUCCESS = "ADD_ROLE_SUCCESS";
export const ADD_ROLE_FAIL = "ADD_ROLE_FAIL";

//Edit or Update Roles

export const UPDATE_ROLE = "UPDATE_ROLE";
export const UPDATE_ROLE_SUCCESS = "UPDATE_ROLE_SUCCESS";
export const UPDATE_ROLE_FAIL = "UPDATE_ROLE_FAIL";

// Delete Roles

export const DELETE_ROLE = "DELETE_ROLE";
export const DELETE_ROLE_SUCCESS = "DELETE_ROLE_SUCCESS";
export const DELETE_ROLE_FAIL = "DELETE_ROLE_FAIL";
