/* USERS */
export const GET_USERS = "GET_USERS";
export const GET_GROUPS = "GET_GROUPS";
export const GET_APPROVERS = "GET_APPROVERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";
export const GET_APPROVERS_SUCCESS = "GET_APPROVERS_SUCCESS";
export const GET_GROUPS_SUCCESS = "GET_GROUPS_SUCCESS";
export const GET_APPROVERS_FAIL = "GET_APPROVERS_FAIL";
export const GET_GROUPS_FAIL = "GET_GROUPS_FAIL";

/* USERS PROFILE */
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_APPROVER_PROFILE = "GET_APPROVER_PROFILE";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_APPROVER_PROFILE_SUCCESS = "GET_APPROVER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAIL = "GET_USER_PROFILE_FAIL";
export const GET_APPROVER_PROFILE_FAIL = "GET_APPROVER_PROFILE_FAIL";

/**
 * add user
 */
export const ADD_NEW_USER = "ADD_NEW_USER";
export const ADD_NEW_APPROVER = "ADD_NEW_APPROVER";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_APPROVER_SUCCESS = "ADD_APPROVER_SUCCESS";
export const ADD_USER_FAIL = "ADD_USER_FAIL";
export const ADD_APPROVER_FAIL = "ADD_APPROVER_FAIL";

/**
 * Edit user
 */
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_APPROVER = "UPDATE_APPROVER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_APPROVER_SUCCESS = "UPDATE_APPROVER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
export const UPDATE_APPROVER_FAIL = "UPDATE_APPROVER_FAIL";

/**
 * Delete user
 */
export const DELETE_USER = "DELETE_USER";
export const DELETE_APPROVER = "DELETE_APPROVER";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_APPROVER_SUCCESS = "DELETE_APPROVER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_APPROVER_FAIL = "DELETE_APPROVER_FAIL";

//AssetsManagement

//Get Assets
export const GET_ASSETS = "GET_ASSETS";
export const GET_ASSETS_SUCCESS = "GET_ASSETS_SUCCESS";
export const GET_ASSETS_FAIL = "GET_ASSETS_FAIL";

//Add Assets

export const ADD_NEW_ASSET = "ADD_NEW_ASSET";
export const ADD_ASSET_SUCCESS = "ADD_ASSET_SUCCESS";
export const ADD_ASSET_FAIL = "ADD_ASSET_FAIL";

//Edit or Update Assets

export const UPDATE_ASSET = "UPDATE_ASSET";
export const UPDATE_ASSET_SUCCESS = "UPDATE_ASSET_SUCCESS";
export const UPDATE_ASSET_FAIL = "UPDATE_ASSET_FAIL";

// Delete Assets

export const DELETE_ASSET = "DELETE_ASSET";
export const DELETE_ASSET_SUCCESS = "DELETE_ASSET_SUCCESS";
export const DELETE_ASSET_FAIL = "DELETE_ASSET_FAIL";
