//CompanySettingsManagement

//Get CompanySettings
export const GET_AIENGINE_SETTINGS = "GET_AIENGINE_SETTINGS";
export const GET_AIENGINE_SETTINGS_SUCCESS = "GET_AIENGINE_SETTINGS_SUCCESS";
export const GET_AIENGINE_SETTINGS_FAIL = "GET_AIENGINE_SETTINGS_FAIL";

//Add CompanySettings

export const ADD_NEW_AIENGINE_SETTING = "ADD_NEW_AIENGINE_SETTING";
export const ADD_AIENGINE_SETTING_SUCCESS = "ADD_AIENGINE_SETTING_SUCCESS";
export const ADD_AIENGINE_SETTING_FAIL = "ADD_AIENGINE_SETTING_FAIL";

//Edit or Update CompanySettings

export const UPDATE_AIENGINE_SETTING = "UPDATE_AIENGINE_SETTING";
export const UPDATE_AIENGINE_SETTING_SUCCESS =
  "UPDATE_AIENGINE_SETTING_SUCCESS";
export const UPDATE_AIENGINE_SETTING_FAIL = "UPDATE_AIENGINE_SETTING_FAIL";

// Delete CompanySettings

export const DELETE_AIENGINE_SETTING = "DELETE_AIENGINE_SETTING";
export const DELETE_AIENGINE_SETTING_SUCCESS =
  "DELETE_AIENGINE_SETTING_SUCCESS";
export const DELETE_AIENGINE_SETTING_FAIL = "DELETE_AIENGINE_SETTING_FAIL";
