export const GET_APPROVERS = "GET_APPROVERS";
export const GET_APPROVERS_SUCCESS = "GET_APPROVERS_SUCCESS";
export const GET_APPROVERS_FAIL = "GET_APPROVERS_FAIL";

export const GET_APPROVER_PROFILE = "GET_APPROVER_PROFILE";
export const GET_APPROVER_PROFILE_SUCCESS = "GET_APPROVER_PROFILE_SUCCESS";
export const GET_APPROVER_PROFILE_FAIL = "GET_APPROVER_PROFILE_FAIL";

export const ADD_NEW_APPROVER = "ADD_NEW_APPROVER";
export const ADD_APPROVER_SUCCESS = "ADD_APPROVER_SUCCESS";
export const ADD_APPROVER_FAIL = "ADD_APPROVER_FAIL";

export const UPDATE_APPROVER = "UPDATE_APPROVER";
export const UPDATE_APPROVER_SUCCESS = "UPDATE_APPROVER_SUCCESS";
export const UPDATE_APPROVER_FAIL = "UPDATE_APPROVER_FAIL";

export const DELETE_APPROVER = "DELETE_APPROVER";
export const DELETE_APPROVER_SUCCESS = "DELETE_APPROVER_SUCCESS";
export const DELETE_APPROVER_FAIL = "DELETE_APPROVER_FAIL";
