//GroupsManagement

//Get Groups
export const GET_COMPGROUPS = "GET_COMPGROUPS";
export const GET_COMPGROUPS_SUCCESS = "GET_COMPGROUPS_SUCCESS";
export const GET_COMPGROUPS_FAIL = "GET_COMPGROUPS_FAIL";

//Add Groups

export const ADD_NEW_COMPGROUP = "ADD_NEW_COMPGROUP";
export const ADD_COMPGROUP_SUCCESS = "ADD_COMPGROUP_SUCCESS";
export const ADD_COMPGROUP_FAIL = "ADD_COMPGROUP_FAIL";

//Edit or Update Groups

export const UPDATE_COMPGROUP = "UPDATE_COMPGROUP";
export const UPDATE_COMPGROUP_SUCCESS = "UPDATE_COMPGROUP_SUCCESS";
export const UPDATE_COMPGROUP_FAIL = "UPDATE_COMPGROUP_FAIL";

// Delete Groups

export const DELETE_COMPGROUP = "DELETE_COMPGROUP";
export const DELETE_COMPGROUP_SUCCESS = "DELETE_COMPGROUP_SUCCESS";
export const DELETE_COMPGROUP_FAIL = "DELETE_COMPGROUP_FAIL";
